"""Encode a beam table as the ftab.dat read by RADYN's Fokker-Planck beam (ibeam = 8).

Format and behaviour taken from the F-CHROMA distribution of RADYN (manual,
prog/rftab.f, prog/beam.f, input/ftab.dat), read on 2026-10-02:

    * line starting with '*' are comments;
    * first data line:  mbeam [eV]  |charge|  pitch-angle-distribution  pitch-angle sigma
    * second data line: number of rows (at most mtint = 5000)
    * rows:             time [s]  delta  Ec [keV]  F [erg cm^-2 s^-1]
      (note the column order differs from HYDRAD: time, delta, Ec, F);
    * delta and Ec are interpolated with taut splines (tension 5.5) and
      **log10(F)** is interpolated the same way, so F cannot be zero: rftab_fp
      clamps it to 0.1 erg cm^-2 s^-1;
    * RADYN stops if the simulation time exceeds the last row, so the table
      must cover the whole run.

Because log F is interpolated, a linear ramp from the 0.1 floor to 1e10 erg
cm^-2 s^-1 would behave like a late step.  The encoder therefore subdivides every
ramp of the source table into short segments that follow the intended linear
ramp.  The effective energy is then computed with log-linear interpolation
between rows (`radyn_energy_per_area`) and must be compared with the intended
energy.  The real spline of RADYN was NOT executed here (no Fortran compiler or
CDF library yet); the final energy check has to use RADYN's own beam output.
"""
from __future__ import annotations

import math
from typing import List, Tuple

from beam_tables import BeamTable

RADYN_FLUX_FLOOR = 0.1      # erg cm^-2 s^-1, applied by rftab_fp
RADYN_MAX_ROWS = 5000       # mtint in prog/cbeam.
ELECTRON_MASS_EV = 511.0e3

Row = Tuple[float, float, float, float]  # (t, delta, Ec, F)


def _row_at(table: BeamTable, t: float) -> Row:
    f, ec, d = table.at(t)
    return (t, d, ec, max(f, RADYN_FLUX_FLOOR))


def radyn_rows(table: BeamTable, t_end: float, sample_dt: float = 0.02) -> List[Row]:
    """Rows (t, delta, Ec, F) covering [0, t_end]; ramps subdivided every `sample_dt`."""
    if sample_dt <= 0:
        raise ValueError("sample_dt must be > 0")
    if t_end < table.t_last:
        raise ValueError("t_end (%.3g) is before the last row of the table (%.3g)" % (t_end, table.t_last))
    times = [0.0] if table.t_first > 0.0 else []
    for (a, fa, _, _), (b, fb, _, _) in zip(table.rows, table.rows[1:]):
        times.append(a)
        if fa != fb:  # a ramp: follow the linear shape with short segments
            n = max(1, int(math.ceil((b - a) / sample_dt)))
            times += [a + (b - a) * k / n for k in range(1, n)]
    times.append(table.t_last)
    rows = [_row_at(table, t) for t in times]
    if t_end > table.t_last:  # flat tail at the floor, keeping the last row's Ec and delta
        _, last_ec, last_d = table.rows[-1][1], table.rows[-1][2], table.rows[-1][3]
        rows.append((t_end, last_d, last_ec, RADYN_FLUX_FLOOR))
    if len(rows) > RADYN_MAX_ROWS:
        raise ValueError("%d rows exceed RADYN's limit of %d; increase sample_dt"
                         % (len(rows), RADYN_MAX_ROWS))
    return rows


def to_radyn_ftab(table: BeamTable, t_end: float, sample_dt: float = 0.02,
                  mbeam_ev: float = ELECTRON_MASS_EV, charge: float = 1.0,
                  pa_type: int = 2, pa_sigma: float = 0.1, note: str = "") -> str:
    rows = radyn_rows(table, t_end, sample_dt)
    lines = ["* additional line for Joel's version",
             "* mass in eV  abs(charge)   pitch-angle distribution  pitch angle sigma for Gaussian",
             "%dd0 %g %d %g" % (int(mbeam_ev), charge, pa_type, pa_sigma),
             "* generated by src/radyn_ftab.py" + (" - " + note if note else ""),
             "* npts", "%d" % len(rows),
             "* Time      dl     Ec      Flux",
             "*--------------------------------------------"]
    lines += ["%10.4f %8.4f %8.3f %12.4e" % r for r in rows]
    return "\n".join(lines) + "\n"


def parse_radyn_ftab(text: str) -> Tuple[Tuple[float, float, int, float], List[Row]]:
    """Return ((mbeam, charge, patype, pasigma), rows) like rftab_fp reads them."""
    data = [ln.split() for ln in text.splitlines() if ln.strip() and not ln.lstrip().startswith("*")]
    first = data[0]
    head = (float(first[0].lower().replace("d", "e")), float(first[1]), int(first[2]), float(first[3]))
    n = int(data[1][0])
    rows = [tuple(float(x) for x in r[:4]) for r in data[2:2 + n]]
    if len(rows) != n:
        raise ValueError("ftab declares %d rows but has %d" % (n, len(rows)))
    return head, rows  # type: ignore[return-value]


def radyn_energy_per_area(rows: List[Row]) -> float:
    """Integral of F dt [erg cm^-2] assuming log-linear interpolation between rows."""
    total = 0.0
    for (t0, _, _, f0), (t1, _, _, f1) in zip(rows, rows[1:]):
        dt = t1 - t0
        if dt <= 0:
            raise ValueError("ftab times must increase")
        total += f0 * dt if f0 == f1 else (f1 - f0) / math.log(f1 / f0) * dt
    return total
